---
version: '3.0'
services:
  jenkins:
    build:
      context: ./Jenkins-Actions
    container_name: jenkins
    user: root
    privileged: true
    ports:
      - '8080:8080'
      - '50000:50000'
    restart: on-failure
    volumes:
      - 'jenkins-jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './Sample-Project:/var/jenkins_home/workspace/Workflow'
      - './Jenkins-Actions/Actions:/var/jenkins_home/Actions'
volumes:
  jenkins-jenkins_home: {}
...
